export const ADD_TO_CART = "ADD_TO_CART";
export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAIL = "CREATE_CART_FAIL";

export const GET_USER_CART_REQUEST = "GET_USER_CART_REQUEST";
export const GET_USER_CART_SUCCESS = "GET_USER_CART_SUCCESS";
export const GET_USER_CART_FAIL = "GET_USER_CART_FAIL";

export const EMPTY_USER_CART_REQUEST = "EMPTY_USER_CART_REQUEST";
export const EMPTY_USER_CART_SUCCESS = "EMPTY_USER_CART_SUCCESS";
export const EMPTY_USER_CART_FAIL = "EMPTY_USER_CART_FAIL";
