export const CATEGORY_LIST_REQUESTS = "CATEGORY_REQUESTS";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_FAIL";

export const CATEGORY_READ_SUCCESS = "CATEGORY_READ_REQUESTS";
export const CATEGORY_READ_FAIL = "CATEGORY_READ_REQUESTS";

export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";

export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_REQUESTS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_REQUESTS";

export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_REQUESTS";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_REQUESTS";

export const GET_CHILD_CATEGORY_SUCCESS = "GET_CHILD_CATEGORY_SUCCESS";
export const GET_CHILD_CATEGORY_FAIL = "GET_CHILD_CATEGORY_FAIL";
