export const CREATE_COUPON_REQUESTS = "CREATE_COUPON_REQUESTS";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL";

export const LIST_COUPON_REQUESTS = "LIST_COUPON_REQUESTS";
export const LIST_COUPON_SUCCESS = "LIST_COUPON_SUCCESS";
export const LIST_COUPON_FAIL = "LIST_COUPON_FAIL";

export const DELETE_COUPON_REQUESTS = "DELETE_COUPON_REQUESTS";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL";

export const APPLY_COUPON_REQUESTS = "APPLY_COUPON_REQUESTS";
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_FAIL = "APPLY_COUPON_FAIL";
