export const ORDER_HISTORY_REQUESTS = "ORDER_HISTORY_REQUESTS";
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS";
export const ORDER_HISTORY_FAIL = "ORDER_HISTORY_FAIL";

export const CREATE_ORDER_REQUESTS = "CREATE_ORDER_REQUESTS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
