export const CREATE_PAYMENT_INTENT_REQUESTS = "CREATE_PAYMENT_INTENT_REQUESTS";
export const CREATE_PAYMENT_INTENT_SUCCESS = "CREATE_PAYMENT_INTENT_SUCCESS";
export const CREATE_PAYMENT_INTENT_FAIL = "CREATE_PAYMENT_INTENT_FAIL";
