export const ALL_PRODUCTS_REQUESTS = "ALL_PRODUCTS_REQUESTS";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const PRODUCTS_CREATE_REQUESTS = "PRODUCTS_CREATE_REQUESTS";
export const PRODUCTS_CREATE_SUCCESS = "PRODUCTS_CREATE_SUCCESS";
export const PRODUCTS_CREATE_FAIL = "PRODUCTS_CREATE_FAIL";

export const PRODUCTS_DELETE_REQUESTS = "PRODUCTS_DELETE_REQUESTS";
export const PRODUCTS_DELETE_SUCCESS = "PRODUCTS_DELETE_SUCCESS";
export const PRODUCTS_DELETE_FAIL = "PRODUCTS_DELETE_FAIL";

export const PRODUCTS_SINGLE_REQUESTS = "PRODUCTS_SINGLE_REQUESTS";
export const PRODUCTS_SINGLE_SUCCESS = "PRODUCTS_SINGLE_SUCCESS";
export const PRODUCTS_SINGLE_FAIL = "PRODUCTS_SINGLE_FAIL";

export const PRODUCTS_UPDATE_REQUESTS = "PRODUCTS_UPDATE_REQUESTS";
export const PRODUCTS_UPDATE_SUCCESS = "PRODUCTS_UPDATE_SUCCESS";
export const PRODUCTS_UPDATE_FAIL = "PRODUCTS_UPDATE_FAIL";

export const PRODUCTS_LIST_REQUESTS = "PRODUCTS_LIST_REQUESTS";
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS";
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL";

export const PRODUCTS_BESTSELLER_REQUESTS = "PRODUCTS_BESTSELLER_REQUESTS";
export const PRODUCTS_BESTSELLER_SUCCESS = "PRODUCTS_BESTSELLER_SUCCESS";
export const PRODUCTS_BESTSELLER_FAIL = "PRODUCTS_BESTSELLER_FAIL";

export const PRODUCTS_COUNT_REQUESTS = "PRODUCTS_COUNT_REQUESTS";
export const PRODUCTS_COUNT_SUCCESS = "PRODUCTS_COUNT_SUCCESS";
export const PRODUCTS_COUNT_FAIL = "PRODUCTS_COUNT_FAIL";

export const PRODUCTS_STAR_REQUESTS = "PRODUCTS_STAR_REQUESTS";
export const PRODUCTS_STAR_SUCCESS = "PRODUCTS_STAR_SUCCESS";
export const PRODUCTS_STAR_FAIL = "PRODUCTS_STAR_FAIL";

export const RELATED_PRODUCTS_REQUESTS = "RELATED_PRODUCTS_REQUESTS";
export const RELATED_PRODUCTS_SUCCESS = "RELATED_PRODUCTS_SUCCESS";
export const RELATED_PRODUCTS_FAIL = "RELATED_PRODUCTS_FAIL";

export const PRODUCTS_SEARCH_FILTER_REQUESTS =
  "PRODUCTS_SEARCH_FILTER_REQUESTS";
export const PRODUCTS_SEARCH_FILTER_SUCCESS = "PRODUCTS_SEARCH_FILTER_SUCCESS";
export const PRODUCTS_SEARCH_FILTER_FAIL = "PRODUCTS_SEARCH_FILTER_FAIL";
