export const USER_LIST_REQUESTS = "USER_LIST_REQUESTS";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_CREATE_REQUESTS = "USER_CREATE_REQUESTS";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_DELETE_REQUESTS = "USER_DELETE_REQUESTS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const SINGLE_USER_REQUESTS = "SINGLE_USER_REQUESTS";
export const SINGLE_USER_SUCCESS = "SINGLE_USER_SUCCESS";
export const SINGLE_USER_FAIL = "SINGLE_USER_FAIL";

export const USER_UPDATE_REQUESTS = "USER_UPDATE_REQUESTS";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_ADDRESS_REQUESTS = "USER_ADDRESS_REQUESTS";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
export const USER_ADDRESS_FAIL = "USER_ADDRESS_FAIL";

export const USER_HISTORY_REQUESTS = "USER_HISTORY_REQUESTS";
export const USER_HISTORY_SUCCESS = "USER_HISTORY_SUCCESS";
export const USER_HISTORY_FAIL = "USER_HISTORY_FAIL";
